version: '3.8'
services:
  web:
    build:
      context: .
      args:
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASS=${DB_PASS}
          - DB_HOST=${DB_HOST}
          - DB_PORT=${DB_PORT}
          - LICENSE_PORT=${LICENSE_PORT}
          - LICENSE_PORT_EXTERNAL=${LICENSE_PORT_EXTERNAL}
          - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "${LICENSE_PORT_EXTERNAL}:${LICENSE_PORT_EXTERNAL}"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  db-data:
